# Generated by Django 3.1.2 on 2020-12-01 03:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import docs.utility


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('docx_file', models.FileField(upload_to=docs.utility.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])], verbose_name='DOCX File')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
