# Generated by Django 3.1.2 on 2020-12-02 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_templateform_templateformentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemplateForm',
            new_name='TemplateFormModel',
        ),
        migrations.RenameField(
            model_name='templateformentry',
            old_name='template_form',
            new_name='template_form_model',
        ),
    ]
