# Generated by Django 3.1.2 on 2020-12-02 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20201202_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemplateFormModel',
            new_name='TemplateSchema',
        ),
        migrations.RenameModel(
            old_name='TemplateFormEntry',
            new_name='TemplateSchemaEntry',
        ),
        migrations.RenameField(
            model_name='templateschemaentry',
            old_name='template_form_model',
            new_name='template_schema',
        ),
    ]
