# Generated by Django 3.1.2 on 2020-12-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_templateschema_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateschema',
            name='name',
            field=models.CharField(default='TestForm001', max_length=50),
            preserve_default=False,
        ),
    ]
