# Generated by Django 3.1.2 on 2020-12-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_templateschema_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateschemaentry',
            name='entry_type',
            field=models.CharField(choices=[('SHORT', 'Short'), ('LONG', 'Long'), ('BOOL', 'True/False')], default='SHORT', max_length=10),
        ),
    ]
