# Generated by Django 3.1.2 on 2020-12-04 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0007_templateschemaentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateschemaentry',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='EntrySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('template_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.templateschema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_short', models.CharField(max_length=50)),
                ('value_long', models.TextField(max_length=800)),
                ('value_bool', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('entryset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.entryset')),
                ('schema_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.templateschemaentry')),
            ],
        ),
    ]
