# Generated by Django 3.1.2 on 2020-12-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_auto_20201204_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='value_bool',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='value_long',
            field=models.TextField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='entry',
            name='value_short',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
