# Generated by Django 3.1.2 on 2020-12-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_auto_20201204_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateschemaentry',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='templateschemaentry',
            constraint=models.UniqueConstraint(fields=('template_schema', 'key'), name='unique key'),
        ),
    ]
