# Generated by Django 3.1.2 on 2020-12-16 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_auto_20201209_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateschema',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.template'),
        ),
    ]
