# Generated by Django 3.1.2 on 2021-01-01 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_auto_20201226_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='description',
        ),
    ]
