# Generated by Django 3.1.2 on 2021-01-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_remove_template_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateschema',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
