# Generated by Django 3.1.2 on 2021-01-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0014_templateschema_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateschemaentry',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
